---
jobs:
  include:
    - stage: test
      services:
        - docker
      script: docker-compose up -d
      after_script: docker-compose logs

    - install:
        # Install a custom version of shellcheck instead of Travis CI's ancient default
        - scversion="stable"
        - wget "https://storage.googleapis.com/shellcheck/shellcheck-$scversion.linux.x86_64.tar.xz"
        - tar --xz -xvf "shellcheck-$scversion.linux.x86_64.tar.xz"
        - shellcheck() { "shellcheck-$scversion/shellcheck" "$@"; }
        - shellcheck --version
      script: shellcheck -x ./borgmatic/*-backup.example

    - install:
        # Install a custom version of shellcheck instead of Travis CI's ancient default
        - scversion="stable"
        - wget "https://storage.googleapis.com/shellcheck/shellcheck-$scversion.linux.x86_64.tar.xz"
        - tar --xz -xvf "shellcheck-$scversion.linux.x86_64.tar.xz"
        - shellcheck() { "shellcheck-$scversion/shellcheck" "$@"; }
        - shellcheck --version
      script: shopt -s globstar && shellcheck -x ./root/**/run
